[flavor]
use = "catppuccin-latte"
[mgr]
cwd = { fg = "#5c6370", italic = true } # 路径颜色，浅灰色


[icon]
rules = [
	# 文件夹使用 Latte 风格的蓝色，对应 Papirus 的经典蓝
	{ name = "*/", text = "󰉋", fg = "#1e66f5" }, 
	
	# 文档类 - 柔和的绿色
	{ name = "*.md",   text = "", fg = "#40a02b" },
	{ name = "*.pdf",  text = "󰈦", fg = "#d20f39" }, # 红色但偏柔和
	
	# 多媒体 - 莫兰迪紫色/橙色
	{ name = "*.jpg",  text = "󰈟", fg = "#fe640b" },
	{ name = "*.png",  text = "󰈟", fg = "#fe640b" },
	{ name = "*.mp3",  text = "󰎆", fg = "#8839ef" },
	
	# 压缩包 - 黄褐色
	{ name = "*.zip",  text = "󰗄", fg = "#df8e1d" },
]

[preview]
# 预览窗格的背景和边框
border = { fg = "#e5e9f0" }
