# [open]
# prepend_rules = [
# 	{ name = "*.json", use = "edit" },
#
# 	# Multiple openers for a single rule
# 	{ name = "*.html", use = [ "open", "edit" ] },
# ]
# append_rules = [
# 	{ name = "*", use = "my-fallback" },
# ]
#

[opener]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
edit = [
	{ run = 'nvim "$@"', block = true, desc = "Edit with Neovim" }
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]
# ...


[preview]
image_filter = "lanczos3"
image_quality = 90
max_width = 1500
max_height = 1500

